Add missing override serve object definition
The following Error was being thrown when using config.json:
Message: NoMethodError: undefined method `[]=' for nil:NilClass